# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LaneBatchUpdateTool
                                 A QGIS plugin
 	自动读取左侧 lane、lane_node、INTERSECTION 图层，批量计算 speedlimit 限速、VIRTUAL 转向字段
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-19
        copyright            : (C) 2026 by xiaocici
        email                : 2774480158@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LaneBatchUpdateTool class from file LaneBatchUpdateTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lanebatchupdate import LaneBatchUpdateTool
    return LaneBatchUpdateTool(iface)
